### ISSUE TITLE
esprima.error_handler.Error: Line 1: Unexpected token :

### ISSUE THREAD

**Issue by kercos** [radian-software/unzuckify#3] opened 2023-12-16 08:17 UTC
when running 
`unzuckify.py -u xxx@gmail.com -p xxx -v inbox`
I get the following:

```
Traceback (most recent call last):
  File "/Users/xxx/Code/unzuckify/./unzuckify.py", line 424, in <module>
    main()
  File "/Users/xxx/Code/unzuckify/./unzuckify.py", line 420, in main
    do_main(args)
  File "/Users/xxx/Code/unzuckify/./unzuckify.py", line 391, in do_main
    inbox_data = get_inbox_data(inbox_js)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/./unzuckify.py", line 236, in get_inbox_data
    esprima.parseScript(inbox_js, delegate=delegate)
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/esprima.py", line 100, in parseScript
    return parse(code, options, delegate, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/esprima.py", line 79, in parse
    ast = parser.parseModule() if isModule else parser.parseScript()
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 2867, in parseScript
    body.append(self.parseStatementListItem())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 1558, in parseStatementListItem
    statement = self.parseStatement()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 2292, in parseStatement
    statement = self.parseBlock()
                ^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 1570, in parseBlock
    block.append(self.parseStatementListItem())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 1558, in parseStatementListItem
    statement = self.parseStatement()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 2287, in parseStatement
    statement = self.parseExpressionStatement()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 1820, in parseExpressionStatement
    self.consumeSemicolon()
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 535, in consumeSemicolon
    self.throwUnexpectedToken(self.lookahead)
  File "/Users/xxx/Code/unzuckify/.venv/lib/python3.11/site-packages/esprima/parser.py", line 237, in throwUnexpectedToken
    raise self.unexpectedTokenError(token, message)
esprima.error_handler.Error: Line 1: Unexpected token :
```

**Comment by raxod502** [comment] 2023-12-22 03:29
This is a duplicate of #2.

**Closed as completed by raxod502** 2023-12-22 03:29 UTC
